"""File discovery and filtering for vulnerability scanning."""

import subprocess
from dataclasses import dataclass
from pathlib import Path

# Extensions we care about, mapped to language names
LANGUAGE_MAP: dict[str, str] = {
    ".py": "python",
    ".pyx": "python",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".cc": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".rb": "ruby",
    ".php": "php",
    ".sh": "shell",
    ".bash": "shell",
}

# Directories to always skip (in addition to .gitignore)
SKIP_DIRS: set[str] = {
    "node_modules",
    "vendor",
    "third_party",
    "3rdparty",
    "external",
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "env",
    ".tox",
    ".nox",
    "build",
    "dist",
    ".eggs",
    "site-packages",
}

# Path patterns that indicate test/doc code (case-insensitive check)
SKIP_PATTERNS: list[str] = [
    "/test/",
    "/tests/",
    "/testing/",
    "/__tests__/",
    "/test_",
    "_test.",
    "_test_",
    ".test.",
    ".spec.",
    "_spec.",
    "/spec/",
    "/specs/",
    "/docs/",
    "/doc/",
    "/documentation/",
    "/examples/",
    "/example/",
    "/fixtures/",
    "/testdata/",
    "/mock/",
    "/mocks/",
    "/conftest.",
    "/setup.py",
    "/setup.cfg",
]

# Lines in a file that suggest it's generated
GENERATED_MARKERS: list[str] = [
    "DO NOT EDIT",
    "AUTO-GENERATED",
    "AUTOGENERATED",
    "Generated by",
    "generated by",
    "Code generated by",
    "This file is generated",
    "automatically generated",
]

MAX_FILE_SIZE = 500_000  # Skip files larger than 500KB


@dataclass
class SourceFile:
    path: str  # Relative to target_dir
    language: str
    size: int


def discover_files(target_dir: str | Path) -> list[SourceFile]:
    """Discover source files using git ls-files (respects .gitignore)."""
    target = Path(target_dir).resolve()

    # Use git ls-files if it's a git repo, otherwise walk
    try:
        result = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=target,
            capture_output=True,
            text=True,
            check=True,
        )
        paths = result.stdout.strip().splitlines()
    except (subprocess.CalledProcessError, FileNotFoundError):
        # Fallback: walk the directory
        paths = []
        for p in target.rglob("*"):
            if p.is_file():
                paths.append(str(p.relative_to(target)))

    files = []
    for rel_path in paths:
        full = target / rel_path
        if not full.is_file():
            continue

        # Check extension
        ext = full.suffix.lower()
        language = LANGUAGE_MAP.get(ext)
        if language is None:
            continue

        # Check skip dirs
        parts = Path(rel_path).parts
        if any(p in SKIP_DIRS for p in parts):
            continue

        # Check skip patterns
        rel_lower = rel_path.lower()
        if any(pat in rel_lower for pat in SKIP_PATTERNS):
            continue

        # Check file size
        try:
            size = full.stat().st_size
        except OSError:
            continue
        if size > MAX_FILE_SIZE or size == 0:
            continue

        # Check for generated file markers (first 5 lines)
        if _is_generated(full):
            continue

        files.append(SourceFile(path=rel_path, language=language, size=size))

    files.sort(key=lambda f: f.path)
    return files


def _is_generated(path: Path) -> bool:
    try:
        with open(path, "r", errors="ignore") as f:
            for i, line in enumerate(f):
                if i >= 5:
                    break
                if any(marker in line for marker in GENERATED_MARKERS):
                    return True
    except OSError:
        pass
    return False
